# Generated by Django 5.0.2 on 2024-03-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubezpieczenia_app', '0004_insurenceagency_alter_client_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='InsurenceAgency',
        ),
    ]
